"""create initial tables

Revision ID: 9c130abc5ea9
Revises: 
Create Date: 2026-07-08 15:21:15.764306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c130abc5ea9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='tech', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'tech')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('test_type', sa.String(length=80), nullable=False),
    sa.Column('received_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='received', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='routine', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('routine', 'urgent', 'repeat')", name='ck_samples_priority'),
    sa.CheckConstraint("status IN ('received', 'processing', 'qc_review', 'resulted', 'cancelled')", name='ck_samples_status'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_id'), 'samples', ['id'], unique=False)
    op.create_index('ix_samples_is_deleted', 'samples', ['is_deleted'], unique=False)
    op.create_index('ix_samples_received_date', 'samples', ['received_date'], unique=False)
    op.create_index(op.f('ix_samples_sample_id'), 'samples', ['sample_id'], unique=True)
    op.create_index('ix_samples_status_test_type', 'samples', ['status', 'test_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_db_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_db_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_sample_created', 'audit_logs', ['sample_db_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_sample_db_id'), 'audit_logs', ['sample_db_id'], unique=False)
    op.create_table('qc_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_db_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=40), server_default='general', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("note_type IN ('failed_control', 'repeat_needed', 'missing_info', 'instrument_issue', 'general')", name='ck_qc_notes_note_type'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_db_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_notes_id'), 'qc_notes', ['id'], unique=False)
    op.create_index(op.f('ix_qc_notes_sample_db_id'), 'qc_notes', ['sample_db_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_notes_sample_db_id'), table_name='qc_notes')
    op.drop_index(op.f('ix_qc_notes_id'), table_name='qc_notes')
    op.drop_table('qc_notes')
    op.drop_index(op.f('ix_audit_logs_sample_db_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_sample_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_samples_status_test_type', table_name='samples')
    op.drop_index(op.f('ix_samples_sample_id'), table_name='samples')
    op.drop_index('ix_samples_received_date', table_name='samples')
    op.drop_index('ix_samples_is_deleted', table_name='samples')
    op.drop_index(op.f('ix_samples_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
